[package]
name = "wayland"
version = "0.1.0"
edition = "2024"

[dependencies]
smithay-client-toolkit = "0.19.2"

anyhow.workspace = true
nalgebra.workspace = true
pollster.workspace = true
wgpu.workspace = true
