[package]
name = "macintosh_wallpaper"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
bitvec = "1.0.1"
encase = { version = "0.10.0", features = ["nalgebra"] }
image = "0.25.6"
tufa = "0.1.2"
