[background]
colormap = "color.png"
duration = 60.0

[scenes]
camera_pos = [ 0.0, 0.0, -1.3 ]
camera_dir = [ -0.40, 1.26, 1.06 ]

scale = 4.0
cutoff = 0.43

progress = 0.0
progress_angle = 0.0

[[scenes.scene]]
frames = [ "images/image-1.png" ]
duration = 16.0

# camera_dir = [ -0.35, 1.05, 1.12 ]
camera_dir = [ -0.40, 1.26, 1.06 ]
progress_angle = 3.14

keyframes = [
    { t = 0.0, camera_pos = [ -1.6, -0.43, -1.3 ], progress = 1.72 },
    { t = 5.0, progress = 30.0 },
    { t = 10.0, progress = 30.0, progress_angle = 3.14 },
    { t = 10.0, progress = 12.5, progress_angle = 0.0 },
    { t = 15.0, camera_pos = [ 1.5, -0.43, -1.3 ], progress = -15.78 },
]

[[scenes.scene]]
frames = [ "images/image-2.png" ]
duration = 16.0

# camera_dir = [ 0.35, 1.05, 1.12 ]
camera_dir = [ 0.40, 1.26, 1.06 ]
progress_angle = 3.14

keyframes = [
    { t = 0.0, camera_pos = [ -2.85, -4.85, -1.3 ], progress = -0.11 },
    { t = 5.0, progress = 28.17 },
    { t = 10.0, progress = 28.17, progress_angle = 3.14 },
    { t = 10.0, progress = 16.25, progress_angle = 0.0 },
    { t = 15.0, camera_pos = [ 0.25, -4.85, -1.3 ], progress = -15.0 },
]

[[scenes.scene]]
frames = [ "images/image-3.png" ]
duration = 16.0

scale = 3
camera_dir = [ 0.40, 1.26, 1.06 ]
progress_angle = 3.14

keyframes = [
    { t = 0.0, camera_pos = [ -2.75, -3.55, -1.30 ], progress = -0.05 },
    { t = 5.0, progress = 28.23 },
    { t = 10.0, progress = 28.23, progress_angle = 3.14 },
    { t = 10.0, progress = -6.0, progress_angle = 0.0 },
    { t = 15.0, camera_pos = [ 0.6, -3.55, -1.30 ], progress = -21.0 }
]
