[background]
colormap = "color.png"
duration = 60.0

[scenes]
camera_pos = [ 0.0, 0.0, -1.3 ]
camera_dir = [ -0.40, 0.93, 1.11 ]

scale = 4.0
cutoff = 0.43

progress = 0.0
progress_angle = 0.0

[[scenes.scene]]
image = "image.png"
duration = 15.0

camera_dir = [ -0.35, 1.05, 1.12 ]
progress_angle = 3.14

keyframes = [
    { t = 0.0, camera_pos = [ -1.6, -0.23, -1.3 ], progress = 1.72 },
    { t = 5.0, progress = 30.0 },
    { t = 10.0, progress = 30.0, progress_angle = 3.14 },
    { t = 10.0, progress = 12.5, progress_angle = 0.0 },
    { t = 15.0, camera_pos = [ 1.5, -0.23, -1.3 ], progress = -15.78 },
]
